name: CI/CD
on:
  push:
    branches:
      - 'name/*'
  pull_request:
    branches:
      - 'name/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2
      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      # Install dependencies
      - name: Install dependencies
        run: npm install
    # Run tests if the test file exists
      - name: Run tests if test file exists
        run: |
         if [ -f path/to/your/test/file.js ]; then
         npm test
         else
         echo "No test file found. Skipping tests."
         fi
      # Build the project
      - name: Build project
        run: npm run build
      # Validate branch name
      - name: Validate branch name
        if: "!startsWith(github.ref, 'refs/heads/name/')"
        run: |
          echo "Branch name does not follow the required pattern."
          exit 1
